name: Cores test

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Build Image
      run: make build-docker 

    - name: Test cores
      run: make test DUT=comp_bin_despl
